apiVersion: v1
kind: Service
metadata:
  name: converter-service-app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: converter-service-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000