apiVersion: v1
kind: Service
metadata:
  name: converter-service
  namespace: default
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: converter-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8090
