apiVersion: batch/v1
kind: Job
metadata:
  name: converter-service
  namespace: default
  labels:
    app: converter-service
    app.kubernetes.io/name: converter-service
spec:
  template:
    spec:
      containers:
      - name: converter-service
        image: sullivl/converter-service:0.0.3
        ports:
        - containerPort: 8090
      restartPolicy: OnFailure
